### ISSUE TITLE
Check how versioning works for xplatform api docs

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-xplat-docs#1043]

**Comment by MayaKirova** [comment]
How it works for Angular Api docs:

1)	The  release build that runs for angular-docs: https://infragistics.visualstudio.com/NetAdvantage/_build?definitionId=16

This triggers Octopus deploy.

2)	That triggers a post deploy script: https://github.com/IgniteUI/igniteui-angular/blob/master/angularDocsPostDeploy.ps1

This creates folders and updates the angular-api-docs-versions.json with all  api docs versions on the staging/release machines.

3)	The drop down uses this code: https://github.com/IgniteUI/ig-typedoc-theme/blob/master/src/assets/js/src/versioning/tag-versions.req.js

Which basically makes request to the json file which holds all versions. 

There’s also a config file with all urls for dev/staging/prod:
https://github.com/IgniteUI/ig-typedoc-theme/blob/master/config.json

**Comment by MayaKirova** [comment]
Idea for similar workflow for react/wc (in short):

1) Add a new Stage to the exiting React/WC Release pipeline that will:
- Retrieve the typedoc zip.
- Deploy to a versioned directory to the staging/prod machines via a Powershell script. Also create/update  the related "*versions.json" with the version info. Also update "latest" if needed.

2. Remove the specific WC/React ApiDocs release pipe(https://infragistics.visualstudio.com/NetAdvantage/_release?_a=releases&view=mine&definitionId=42) as it will now be obsolete.
