### ISSUE TITLE
Automatic Xplat processes push changes with wrong API docs URLs

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-xplat-docs#1078]
Observe this PR made by the automatic process to pr changes to Angular Docs: https://github.com/IgniteUI/igniteui-docfx/pull/3909

The API links start with `undefined` instead of component name and are therefore broken.

**Comment by HUSSAR-mtrela** [comment]
Graham is going to update API generator and fix issue with missing package names in API mapping files:

![image](https://github.com/IgniteUI/igniteui-xplat-docs/assets/11665978/8b05aaf3-adda-4c72-a8a2-7976d1bafbe7)

**Comment by HUSSAR-mtrela** [comment]
this issues should be fixed by PR #1110 
and a new PR targeting Angular should be generated by this build:
https://infragistics.visualstudio.com/NetAdvantage/_build/results?buildId=128606&view=results

**Comment by HUSSAR-mtrela** [comment]
fixed on staging
