### ISSUE TITLE
Broken API links in WebComponent docs

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-xplat-docs#1092]
**Here is the list of broken links :** 

NOTE ignore items that are ~~Strikethrough~~

1.https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/general-changelog-dv-wc

These links are broken from the page:
https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igniteui_webcomponents_grids_grids.igccolumn.html
https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/enums/NaNdatagridselectionmode.html
https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/enums/NaNeditmodeclickaction.html

~~GridSelectionMode propertyPath : missing link~~

2.https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/general-cli-overview

ig version: missing link 

**Grid:**
https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/cell-editing

•	[IgcGridRow](https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igniteui_webcomponents_grids_grids.igcgridrow.html), [IgcCell](https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igniteui_webcomponents_grids_grids.igccell.html): 404 error

~~DatePickerComponent, CellEdit: missing links~~

**Excel**
https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/export-excel
•	~~ExporterOption ,IgnoreMultiColumnHeaders , ExporterOption ,FreezeHeaders, ExcelExporterService ,ExcelExporterOptions: missing links~~

•	[Grid API](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/%7Benvironment:dvdemosbaseurl%7D/classes/grid.md),[Grid Styles](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/%7Benvironment:sassApiUrl%7D/index#function-grid-theme)   :404 error

https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/display-density
•	[displayDensity](https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igniteui_webcomponents_grids_grids.igcdisplaydensitybasecomponent.html#displayDensity) , [IgcColumn](https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igniteui_webcomponents_grids_grids.igccolumn.html) :404 error

https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/multi-column-headers
[IgcColumnGroup](https://staging.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igniteui_webcomponents_grids_grids.igccolumngroup.html) : 404 error

**Input**:
https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/button-group
•	~~ToggleButton, ButtonGroup , ButtonGroup, ToggleButton and more : Missing links all over the page~~

**Layout**:
https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/dock-manager
- ~~allowFloatingPanesResize , floatingPanes , floatingResizable : Missing links from ‘floating pane’ section~~
- ~~ActivePaneChanged,PaneClose ,closeButton, maximizeButton, minimizeButton, pinButton and unpinButton  :  Missing link from all over the page~~

- ~~All ‘Slot name’ and ‘CSS variable’,’CSS Parts’ doesn’t have links~~

**Comment by HUSSAR-mtrela** [comment]
should be fixed in the next build
