### ISSUE TITLE
'PackageVerChangedFields' is visible in the breaking-changes Angular topic content

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-xplat-docs#13]
Open the [General breaking changes dv topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general-breaking-changes-dv) and scroll down to Changed name of Property path.

Result:
![image](https://user-images.githubusercontent.com/11193764/100356492-fba31d80-2ffb-11eb-9f2b-94abbe0d11f5.png)

**Comment by HUSSAR-mtrela** [comment]
@mddifilippo89 can you fix this issue by build flagging that section of topic for React, and WC platforms ?

**Comment by HUSSAR-mtrela** [comment]
this topic was replaced by 
https://www.infragistics.com/products/ignite-ui-angular/angular/components/general-changelog-dv
