### ISSUE TITLE
Add Divider docs and samples

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-xplat-docs#1314]
Spec available [here](https://github.com/IgniteUI/igniteui-webcomponents/wiki/Divider).

Add section how divider can be used in dropdown/selection topics since this is a reasonable scenario when divider functionality  could be illustrated.

**Comment by radomirchev** [comment]
@kacheshmarova , @IvanKitanov17 the docs and samples are not present to staging and this blocks preparation of marketing materials. When I can expect them available on staging?

**Comment by dkamburov** [comment]
@kacheshmarova @IvanKitanov17 I can't find samples for the divider for Blazor and React. Is that on purpose?
