### ISSUE TITLE
TreeGrid Selection topics are not ordered correctly in the Navigation Menu

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-xplat-docs#1321]
![image](https://github.com/IgniteUI/igniteui-xplat-docs/assets/52423497/9a1309ab-dd35-47ba-be0c-188db19d4a79)

They should be ordered as follows:
![image](https://github.com/IgniteUI/igniteui-xplat-docs/assets/52423497/cbd239ea-cb5e-41a7-9fc1-3283a95f8277)

**Comment by georgianastasov** [comment]
The issue of TreeGrid Selection topics not being ordered correctly in the Navigation Menu has been resolved in [this PR](https://github.com/IgniteUI/igniteui-xplat-docs/pull/1315).
