### ISSUE TITLE
State Persistence Topic missing for WC, React, Blazor Tree and Hierarchical Grids

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-docs#1334]
State Persistence feature is supported for WC, Blazor and React Tree and Hierarchical Grids but the documentation and samples are missing. Our clients can find out the feature is present only by chance!

**Comment by mddragnev** [comment]
NOTE: Pivot grid is waiting for a new build. Blazor is waiting for a merge of a fix.
