### ISSUE TITLE
Missing samples and topic for the divider for Blazor and React

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-xplat-docs#1369]
@kacheshmarova @IvanKitanov17 I can't find samples for the divider for Blazor and React. Is that on purpose?

_Originally posted by @dkamburov in https://github.com/IgniteUI/igniteui-xplat-docs/issues/1314#issuecomment-2331774928_

**Comment by IvanKitanov17** [comment]
@dkamburov The Divider was not released for Blazor and React, when I was making the samples. I am going to create the samples today.
