### ISSUE TITLE
Sparkline's chart demo is broken

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-xplat-docs#169]
1. Navigate to [Sparkline topic (on staging)](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/charts/types/sparkline-chart)
2. Check the demo

Result: The markdown is broken and code-view snippet shows up as text.
Expected result: The demo should be shown.

![image](https://user-images.githubusercontent.com/16817847/136012724-486476c3-9ccc-4414-8a33-582c8fd79fa7.png)

**Comment by HUSSAR-mtrela** [comment]
should be fixed in the next build
