### ISSUE TITLE
Some angular dv samples do not load

### ISSUE THREAD

**Issue by dobromirts** [IgniteUI/igniteui-xplat-docs#22]
For example the samples in [Angular Configuration Options](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/category-chart-config-options) and [Angular Legends](https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-legends)
do not load. The src link for the sample in the iframe cannot match any routes.

**Comment by mddifilippo89** [comment]
fixed

**Comment by HUSSAR-mtrela** [comment]
not fixed until it is actually fixed on production.

**Comment by HUSSAR-mtrela** [comment]
these topics were removed
