### ISSUE TITLE
Create a new angular pie charts topic

### ISSUE THREAD

**Issue by aatanasov2** [IgniteUI/igniteui-xplat-docs#24]
[New copy ](https://infragisticsinc297.sharepoint.com/:w:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7BC4C53485-0611-41D4-BD6F-493CF91B37F0%7D&file=Angular%20pie%20chart%20structure.docx&action=default&mobileredirect=true&cid=c5dc0802-1963-45d9-966e-aed2401d7e15)

**Comment by HUSSAR-mtrela** [comment]
already completed
