### ISSUE TITLE
Broken link in Grid > Column Filtering topic

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-xplat-docs#279]
1. Navigate to https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/data-grid-column-filtering
2. Check links

Result: "Filter expression" link is broken.

**Comment by HUSSAR-mtrela** [comment]
@mddifilippo89 can you fix broken "Filter expression" link by adding required class/enum name to the `mentionedTypes` array?
