### ISSUE TITLE
Broken links in "Changelog" topic

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-xplat-docs#281]
1. Navigate to https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/general-changelog-dv
2. Check the links in Data Grid section

![image](https://user-images.githubusercontent.com/16817847/146541422-3bd56178-8858-432b-b6c4-33e120876b5b.png)

**Comment by mddifilippo89** [comment]
fixed 
https://github.com/IgniteUI/igniteui-xplat-docs/pull/323/commits/d47f720eaa3b04fd7a470ce85418c90f9523285e
