### ISSUE TITLE
Bug: Scripts don't run on POSIX compliant operating systems

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-xplat-docs#321]
Steps to reproduce:

1. Fire up any POSIX compliant OS(Linux, macOS)
2. Run `npm start` in project root
3. Observe Error log

**Comment by ChronosSF** [comment]
@HUSSAR-mtrela , this is causing issues for many colleagues currently running Macs and cause disruptions in our work process. Could you please work on in with priority?

**Comment by HUSSAR-mtrela** [comment]
@agoldenbaum or @mddifilippo89  can you investigate this issue?

**Comment by mddifilippo89** [comment]
@simeonoff 
Can you post the error log?

**Comment by simeonoff** [comment]
[Here](https://pastebin.com/qsGbdBKC). You can easily replicate it by running `npm run startWC` (or any, really) in a Linux (WSL2) or macOS environment.

**Comment by HUSSAR-mtrela** [comment]
@simeonoff  @mddifilippo89 @ChronosSF 
this issue should be fixed now. let me know if you see similar issue.
