### ISSUE TITLE
IgbDataGrid - the sample code can't build -  CS1061: 'App' does not contain a definition for 'DataSource'

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-xplat-docs#412]
Go to this page - 
EN: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#sample-data-source
JA: https://jp.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB-%E3%83%87%E3%83%BC%E3%82%BF-%E3%82%BD%E3%83%BC%E3%82%B9

The sample code below cusses build error:

"CS1061: 'App' does not contain a definition for 'DataSource' and no accessible extension method 'DataSource' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)"

```
@code {
    public void GenerateData()
    {
        string[] names = new string[] {
            "Intel CPU", "AMD CPU",
            "Intel Motherboard", "AMD Motherboard", "Nvidia Motherboard",
            "Nvidia GPU", "Gigabyte GPU", "Asus
        ....
        this.DataSource = sales; // <-⚠️CS1061
    }
    ...
}
```

**Comment by ymita** [comment]
This build error can be fixed by adding the code like this:

```
@code {
    private IEnumerable<SaleInfo>? DataSource;
    ...
```

**Comment by agoldenbaum** [comment]
This is fixed on staging and should be available publicly in the next production docs push
