### ISSUE TITLE
IgbDataGrid - the sample code can't build -   CS0103: The name 'Rand' does not exist in the current context

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-xplat-docs#413]
Go to the help page - 
EN: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#sample-data-source
JA: https://jp.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB-%E3%83%87%E3%83%BC%E3%82%BF-%E3%82%BD%E3%83%BC%E3%82%B9

The sample code below cusses build error: "CS0103: The name 'Rand' does not exist in the current context"

```
@code {
    ...
    public double GetRandomNumber(double min, double max)
    {
        return Math.Round(min + (Rand.NextDouble() * (max - min))); // <-⚠️CS0103
    }
    ...
}
```

**Comment by ymita** [comment]
This build error can be fixed by changing the identifier to "Random.Shared" from "Rand".

**Comment by agoldenbaum** [comment]
This is fixed on staging and should be available publicly in the next production docs push
