### ISSUE TITLE
IgbDataGrid - the sample code has some warnings about nullable reference type -  CS8618: Non-nullable property '...' must contain a non-null value when exiting constructor.

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-xplat-docs#414]
Go to the following help page:
EN: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#sample-data-source
JA: https://jp.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB-%E3%83%87%E3%83%BC%E3%82%BF-%E3%82%BD%E3%83%BC%E3%82%B9

Then, the sample code below has some warnings about nullable reference type:

"CS8618: Non-nullable property 'Status' must contain a non-null value when exiting constructor. Consider declaring the property as nullable."

```
@code {
    ...
    public class SaleInfo
    {
        public string Status { get; set; } // <- ⚠️CS8618
        public string ProductName { get; set; } // <- ⚠️CS8618
        public string CountryFlag { get; set; } // <- ⚠️CS8618
        public string Country { get; set; } // <- ⚠️CS8618
        public DateTime OrderDate { get; set; }
        public double Profit { get; set; }
        public double ProductPrice { get; set; }
        public double ProductID { get; set; }
        public double OrderValue { get; set; }
        public double OrderItems { get; set; }
        public double Margin { get; set; }
    }
}
```

**Comment by ymita** [comment]
These warnings can be fixed by changing the type of these properties to "string?" from "string".

```
public class SaleInfo
{
    public string? Status { get; set; }
    public string? ProductName { get; set; }
    public string? CountryFlag { get; set; }
    public string? Country { get; set; }
    ...
}
```

**Comment by agoldenbaum** [comment]
This is fixed on staging and should be available publicly in the next production docs push
