### ISSUE TITLE
IgbDataGrid - the sample code shows an empty grid even though after all build errors were fixed.

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-xplat-docs#416]
Because the sample code doesn't contain the code that initialize the "DataSource" property or field.

EN: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#sample-data-source
JA: https://jp.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB-%E3%83%87%E3%83%BC%E3%82%BF-%E3%82%BD%E3%83%BC%E3%82%B9

**Comment by ymita** [comment]
This issue can be fixed by adding initializing code like below:

```
@code {
    ...
    protected override void OnInitialized()
    {
        GenerateData();
    }
    ...
```

**Comment by agoldenbaum** [comment]
This is fixed on staging and should be available publicly in the next production docs push
