### ISSUE TITLE
Getting Started doesn't work

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-xplat-docs#430]
Reference: https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/general-getting-started

## 1. It's too long

This is my first contact with the product and I wish it had something like `git clone` getting started, the step-by-step is painful, it's ok as a sub-topic but not as main topic.

Then I'd like to have a list with only the necessary steps for the product, like installing ignite packages, register the components, set up styling. This will be my go to reference if I need to add ignite to an existing project.

The topic with Ignite CLI makes it a lot simpler, but "Getting started" will always be my first contact with the product and I expect it to be as simple as possible. Getting started could start with: "We recommend kick start your project using <u>Ignite CLI</u> (link here)".

## 2. It mentions the wrong file:

> 2 - Import the Geographic Map modules and ModuleManager in index.ts file:

the only place where `.ts` is mentioned, it should be `.js`.

## 3. It fails to build

```
> npm run build

> wc-html@1.0.0 build
> webpack src/index.js -o dist/index.bundle.js

assets by status 0 bytes [cached] 1 asset

ERROR in main
Module not found: Error: Can't resolve 'src/index.js' in 'C:\Work\wc-html'
Did you mean './src/index.js'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
resolve 'src/index.js' in 'C:\Work\wc-html'
  Parsed request is a module
  using description file: C:\Work\wc-html\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:\Work\wc-html\node_modules
        C:\Work\wc-html\node_modules\src doesn't exist
      C:\Work\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory

webpack 5.74.0 compiled with 1 error in 147 ms
```

When set up as in the docs:
```
  "scripts": {
    "build": "webpack src/index.js -o dist/index.bundle.js"
  },
```
had to change it to: `"webpack ./src/index.js -o ./dist/ --output-filename index.bundle.js"`
 - starting "./" as suggested in the error message.
 - added filename otherwise it produces a "main.js" which is not what the tutorial expects afterwards.

## 5. It misses styling completely

I add a button, npm install it, register it and this is the result:
![image](https://user-images.githubusercontent.com/12942794/185477222-73fd3468-6ded-4d4b-bbad-5e815dff13ce.png)

Getting started should get me to working components and that includes styling.
I need to go find _Styling_ topic to learn that there's a few more steps to get styles working.

**Comment by ChronosSF** [comment]
We'll have to work on point 4 though. I'll see if we can do something about it next sprint.

**Comment by mddifilippo89** [comment]
I followed the steps and everything worked fine except for some details mentioned above. I had to install lit-html. 

https://github.com/IgniteUI/igniteui-xplat-docs/pull/453

**Comment by mddifilippo89** [comment]
At a bare minimum you don't need any styling. It's best if add a new styling topic.

**Comment by pmoleri** [comment]
> At a bare minimum you don't need any styling. It's best if add a new styling topic.

I disagree strongly. Without styling set up the components design is broken.
I shouldn't need to be hunting for topics.

But the bigger problem here is that getting started doesn't include `igniteui-webcomponents` package, so both issues can be addressed in the same task.

@ChronosSF, @mddifilippo89 addressed points 2. and 3.
It's up to you if you want to open an new issue for the rest.

**Comment by pmoleri** [comment]
@ChronosSF more than 1 year later facing the beautiful process of adding ignite components to a project and still no info about styles/themes in the getting started page.

This is how my dropdown looks:
![image](https://github.com/IgniteUI/igniteui-xplat-docs/assets/12942794/682aa638-82c9-4c43-99f5-f719231f9e73)

At some point I remembered this issue and I know where to get the info I need now.

**Comment by kdinev** [comment]
@simeonoff reopening for the styling issue.
