### ISSUE TITLE
Snackbar does not close upon "Close" button click

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-xplat-docs#431]
Steps:
1. Go to https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/notifications/snackbar#action-text
2. Click "Show snackbar" button to show snackbar
3. Click "Close" button
![image](https://user-images.githubusercontent.com/14340675/186111818-cfaaba20-242f-4208-bcbc-8e97032be98a.png)

Result:
Snackbar does not close.

Expected Result:
Snackbar closes.

**Comment by agoldenbaum** [comment]
Marking this as "status:blocked" for a bug with the Action and ActionScript events in the IgbSnackbar. New issue logged here: https://github.com/IgniteUI/igniteui-blazor/issues/31

**Comment by agoldenbaum** [comment]
This is fixed on our staging site and should be available publicly when the next doc push to production happens
