### ISSUE TITLE
Broken link in Blazor DockManager topic

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-docs#433]
1. Visit the "API Members" section of the ["Blazor Dock Manager Overview"](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/dock-manager#api-members) page.
2. You will see the `IgbDockManager` link in the "API Members" section.
3. If you click the `IgbDockManager` link, then you wil run into the "404 - File or directory not found" server error page.

![image](https://user-images.githubusercontent.com/102948935/188379497-b765a9da-e5fd-446f-9096-4063531a6efc.png)

This `IgbDockManager` broken links in "API Members" section are in all of Blazor Dock Manager topic pages as below.

- ["Blazor Dock Manager Overview"](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/dock-manager#api-members)
- ["Blazor Updating Panes in Dock Manager"](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/dock-manager-updating-panes#api-members)
- ["Blazor Embedding Frames in Dock Manager"](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/dock-manager-embedding-frames#api-members)

**Comment by agoldenbaum** [comment]
This appears to have been fixed. Marking this issue closed
