### ISSUE TITLE
The page title of the "Getting Started" page for "Ignite UI for Blazor" seems not appropriate.

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-docs#435]
Currently, the page title of the "Getting Started" page for "Ignite UI for Blazor" is **"Blazor Data Visualization Tools | Blazor Data Visualization Tools | Getting Started | Infragistics"**. But obviously, this page is not about "data visualization".

![image](https://user-images.githubusercontent.com/102948935/188399056-fba74297-6872-48d8-a4e1-6cee5267d733.png)

The title of that page should be more appropriate such as "Getting Started | Ignite UI for Blazor | Infragistics".

The page list of pages that should be improved their page title is as the following.

- ["Getting Started With Ignite UI for Blazor"](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/general-getting-started) ([source code](https://github.com/IgniteUI/igniteui-xplat-docs/blob/vnext/doc/en/components/general-getting-started.md?plain=1#L2))
- ["Getting Started with Ignite UI for Blazor WebAssembly"](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/general-getting-started-blazor-client) ([source code](https://github.com/IgniteUI/igniteui-xplat-docs/blob/vnext/doc/en/components/general-getting-started-blazor-client.md?plain=1#L2))
- ["Getting Started with Ignite UI for Blazor .NET MAUI"](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/general-getting-started-blazor-maui) ([source code](https://github.com/IgniteUI/igniteui-xplat-docs/blob/vnext/doc/en/components/general-getting-started-blazor-maui.md?plain=1#L2))

**Comment by agoldenbaum** [comment]
Marking this closed. I checked in a PR for this and it is on staging
