### ISSUE TITLE
API - Some links in Blazor docs are not working

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-xplat-docs#437]
It seems links to API reference is not working on multiple pages.

> MartinT: @agoldenbaum you will need to ask Graham to re-gen API docs website for LOB Blazor components since the IgbChip is missing AND then queue a new build for Blazor docs.

One example steps to reproduce is as below:
Steps
1. Go to https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/chip#usage
2. Click the link to the API page
![image](https://user-images.githubusercontent.com/14340675/188768513-6d5e1f3a-89e1-417b-94d2-7362d31d2425.png)
3. The page is not found 
![image](https://user-images.githubusercontent.com/14340675/188768573-9711f220-80ae-41fd-8864-e7b3c2d3e51b.png)

The symptom is reproduced on JP page:
https://jp.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/chip#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by ymita** [comment]
There is a similar issue reported.
https://github.com/IgniteUI/igniteui-xplat-docs/issues/433

**Comment by ymita** [comment]
Another example of the issue is on Toast:
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/notifications/toast

![image](https://user-images.githubusercontent.com/14340675/188775100-d2eefafb-de8e-4b84-a82f-fa5d9ae70414.png)

**Comment by HUSSAR-mtrela** [comment]
fixed
