### ISSUE TITLE
Getting Started with Ignite UI for Blazor - .NET MAUI has been GA

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-docs#440]
The ".NET MAUI" has been officially released, so it is no longer pre-release, isn't it?

- [_"Introducing .NET MAUI – One Codebase, Many Platforms"_ (.NET Blog, May 23rd, 2022)](https://devblogs.microsoft.com/dotnet/dotnet-maui-visualstudio-2022-release/)
- [_"Productivity comes to .NET MAUI in Visual Studio 2022"_ (.NET Blog, August 9th, 2022)](https://devblogs.microsoft.com/dotnet/dotnet-maui-visualstudio-2022-release/)

So I think we should remove the remarks below from our ["Getting Started with Ignite UI for Blazor .NET MAUI" page](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/general-getting-started-blazor-maui).

> _.NET Multi-platform App UI (.NET MAUI) is currently in preview. This content relates to a pre-release product that may be substantially modified before it's released. Infragistics makes no warranties, express or implied, with respect to the information provided here._

![image](https://user-images.githubusercontent.com/102948935/189014012-355344cc-b72a-45c4-b794-c5c2b0abec43.png)

**Comment by jsakamotoIGJP** [comment]
Is there any progress about this topic?

**Comment by mddifilippo89** [comment]
@jberes @brianlagunas

**Comment by brianlagunas** [comment]
> @jberes @brianlagunas

@mddifilippo89 What do you need from us in order to update the doc topic?

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-docs/pull/644
