### ISSUE TITLE
The error "TS2769 no overload matches this call" occurs on Workbook.load methods in the Angular Excel Utility.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-xplat-docs#447]
1. Copy the Angular Excel Utility codes in the following page and pasted it to an Angular application.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/excel-utility

Actual:
The error "TS2769 no overload matches this call" occurs on Workbook.load methods in the Angular Excel Utility.
![image](https://user-images.githubusercontent.com/33947244/189591237-f06392eb-e69f-41be-b9f9-234d3a223cc8.png)

Expected:
No error occurs.

See the following reproducible sample.
[kb9030-angular-app1.zip](https://github.com/IgniteUI/igniteui-xplat-docs/files/9545481/kb9030-angular-app1.zip)

**Comment by agoldenbaum** [comment]
This is only happening due to the setting of strict=true in the tsconfig.json in the sample.

Marking this closed.
