### ISSUE TITLE
Yarn startBlazor (and any other platform) throws an error on macOS.

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-xplat-docs#463]
Trying to run the project on macOS throws an error that a file is missing.
![Screenshot 2022-09-27 at 14 53 40](https://user-images.githubusercontent.com/37667452/192518316-5610b044-3744-440c-9fba-97e879b3e41d.png)
This is caused because in the `docComponents.json` file all the outputs have the follow this pattern `\\grid\\`.
Thus, the content after the build is in the wrong directory `dist/Blazor/en/components/grids/\pivot-grid\`.
I was able to fix this with the following change:
![Screenshot 2022-09-27 at 14 56 49](https://user-images.githubusercontent.com/37667452/192518935-99a5946b-3956-4f25-aa86-65a45b0e7cdc.png)
Could you please take a look at this and fix it in windows and macOS?

**Comment by simeonoff** [comment]
@mtrela any timeline on when this will be fixed?

**Comment by mddragnev** [comment]
@simeonoff There is a workaround if you need it right now. Just remove all backslashes from the output property.

**Comment by simeonoff** [comment]
> @simeonoff There is a workaround if you need it right now. Just remove all backslashes from the output property.

Yeah, we've done that.

**Comment by HUSSAR-mtrela** [comment]
it should be fixed in vnext
