### ISSUE TITLE
Missing API links for IgcDropdownComponent, IgcSwitch, IgcTree

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-xplat-docs#468]
All dropdown related links lead to non-existing pages.

1. Go to https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/dropdown
2. Click any API link 

**Result**: "404 File or directory not found"
Example: https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcdropdowncomponent.html

**Comment by HUSSAR-mtrela** [comment]
update API mapping and check links. Might need a new build of API docs

**Comment by HUSSAR-mtrela** [comment]
this should be fixed in this PR https://github.com/IgniteUI/igniteui-xplat-docs/pull/905

**Comment by HUSSAR-mtrela** [comment]
fixed on production
