### ISSUE TITLE
The heading text might not be so appropriate in the "Blazor Webassembly: How To Read & Write Excel Files To Reduce Server Load" page

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-docs#500]
https://github.dev/IgniteUI/igniteui-xplat-docs/blob/ebd7f430493fb3bd8b7de655062b06a5cece7318/doc/en/components/blazor-webassembly-how-to-read-and-write-excel-files-to-reduce-server-load.md#L36 

> How To Create a Blazor WebAssembly App With Ignite UI for Blazor

That heading text might not be so appropriate because that section doesn't explain any "how to" topics.  For example, another header text, "Summary of the sample application," might be more appropriate.

**Comment by HUSSAR-mtrela** [comment]
it provides some "how to" instructions and set up steps
