### ISSUE TITLE
Incorrect file types specification on code blocks in the "Add new blazor topics" pull request.

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-docs#503]
https://github.dev/IgniteUI/igniteui-xplat-docs/blob/ebd7f430493fb3bd8b7de655062b06a5cece7318/doc/en/components/blazor-webassembly-how-to-read-and-write-excel-files-to-reduce-server-load.md#L190-L191 

> ` ```razor `

The file type specification of the code block above the line should be "xml", not "razor". **The above is only one example.** I found so many incorrect file type specifications in [the "Add new blazor topics" pull request](https://github.com/IgniteUI/igniteui-xplat-docs/pull/451). 

I can fix those incorrect file type specifications and **I can also send them as pull requests** on this GitHub repository. What do you think about this idea?

**Comment by HUSSAR-mtrela** [comment]
Blazor docs do not support "xml" language at this moment
