### ISSUE TITLE
Linking to INFRAGISTICS Knowledge Base might not be appropriate

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-docs#505]
https://github.dev/IgniteUI/igniteui-xplat-docs/blob/ebd7f430493fb3bd8b7de655062b06a5cece7318/doc/en/components/blazor-webassembly-how-to-read-and-write-excel-files-to-reduce-server-load.md#L164 

> please refer to the INFRAGISTICS Knowledge Base (link below).

It might be better to link to the new blazor document below instead of the knowledge base.

https://github.com/IgniteUI/igniteui-xplat-docs/blob/vnext/doc/en/components/blazor-excel-library-temporarily-stop-automatic-calculation-of-formulas-to-speed-up-processing.md

**Comment by agoldenbaum** [comment]
Fixed in following PR: https://github.com/IgniteUI/igniteui-xplat-docs/pull/640
