### ISSUE TITLE
The map overview topic has a duplicate paragraph

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-xplat-docs#51]
Open the map topic and navigate to the [required modules section](https://www.infragistics.com/products/ignite-ui-angular/angular/components/geo-map#required-modules). You will see that the first paragraph appears twice.

**Comment by HUSSAR-mtrela** [comment]
@agoldenbaum can you fix this?

**Comment by HUSSAR-mtrela** [comment]
this issue is fixed now
