### ISSUE TITLE
Dialog Blazor Component Documentation

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-docs#552]
There is no topic and samples for Dialog Blazor Component on both staging and production. PR Merged Sep 30 https://github.com/IgniteUI/igniteui-xplat-docs/pull/428

**Comment by HUSSAR-mtrela** [comment]
this topic is excluded because there is no sample for it
https://github.com/IgniteUI/igniteui-blazor-examples/tree/vnext/samples/notifications
