### ISSUE TITLE
Dialog Web Component Documentation

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-docs#554]
There is no topic and samples for Dialog Web Component on both staging and production. PR Merged Sep 30 https://github.com/IgniteUI/igniteui-xplat-docs/pull/428

**Comment by radomirchev** [comment]
Docs are available but have a template issue

https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/notifications/dialog

![image](https://user-images.githubusercontent.com/52001020/199669636-c3fe8c38-22a8-44cc-bb38-ba07e864ae0c.png)

**Comment by HUSSAR-mtrela** [comment]
already fixed
 
![image](https://user-images.githubusercontent.com/11665978/217551363-00a1cf4d-d6c8-4ee1-83d1-706a7c2d3db7.png)
