### ISSUE TITLE
Links to other topics are not correct.

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-xplat-docs#563]
Links to other topics are not correct. Looks like they shouldn't contain .md at the end.

Repro steps:
Open grid overview topic in additional resources click on any of the links
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/overview#additional-resources

**Comment by HUSSAR-mtrela** [comment]
should be fixed in the next build
