### ISSUE TITLE
Column Hiding topic have some information that is only relateable to angular and not blazor atm

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-xplat-docs#564]
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/column-hiding#api-references

In the api reference section there are some things that the topic does not include. Also some directives that do not exist in blazor.

**Comment by HUSSAR-mtrela** [comment]
please list those API members

**Comment by mddifilippo89** [comment]
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/column-hiding#api-references
