### ISSUE TITLE
WC Grid Overview requirements and usage issues

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-xplat-docs#581]
See https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/overview#component-modules

The text and snippet for the modules section are wrong:
```ts
import { ModuleManager } from 'igniteui-webcomponents-core';
import { IgcGridModule } from 'igniteui-webcomponents-grids';
import { IgcGridComponent } from 'igniteui-webcomponents-core';

ModuleManager.register(
    IgcGridModule
);
```
Fairly certain we don't expose such module atm, as in
`'"@infragistics/igniteui-webcomponents-grids"' has no exported member named 'IgcGridModule'`

The sample got it closer, what's needed to load the grid is the bundle, i.e.
`import 'igniteui-webcomponents-grids/grids/combined';`
And the CSS, which can be done like in the samples vie direct import, but that requires app env with CSS loaders configured (not a given). We should probably describe _one_ of the available themes must be loaded with a few examples, since we can't really give a singular right way to do that in WC.

There's also an Angular style assign for `data` in the **Usage** snippet:
```html
<igc-grid id="grid1" [data]="localData" auto-generate="true"></igc-grid>
```
Which should be removed, considering it's followed by a js snippet that shows how to assign data

**Comment by HUSSAR-mtrela** [comment]
@agoldenbaum WC grid does not require registerting modules so you should:

add CSS import

```
import "igniteui-webcomponents-grids/grids/themes/light/bootstrap.css";
```

keep this line above CSS import:

```
import { IgcGridComponent } from 'igniteui-webcomponents-core';
```

remove these lines:
```
import { ModuleManager } from 'igniteui-webcomponents-core';
import { IgcGridModule } from 'igniteui-webcomponents-grids';

ModuleManager.register(
    IgcGridModule
);```
