### ISSUE TITLE
Broken link to CRUD topic

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-docs#586]
Any [page](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/overview#api-references) that has the [Build CRUD operations with Grid](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/general/how-to/how-to-perform-crud.md) link. There seems to be no such file in the xplat repository at the moment, only in igniteui-docfx.

TODO build flag it a platform that has this topic or commented it out.

**Comment by agoldenbaum** [comment]
Fixed on staging
