### ISSUE TITLE
IgbGrid Column pinning topic has incorrect content for pinning a column at a given position

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-docs#589]
goto : https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/column-pinning#column-pinning-api

in blazor you cannot use the ColumnPin event in Blazor to change the order of the pinned columns since setting event args in blazor events is not supported. Instead the PinColumn method can be used passing in the index as the second parameter.

**Comment by IGvaleries** [comment]
if a code snippet is maintained to show how to use insertAtIndex in the evet handler it needs to be done in javascript, for example:
window.onColumnPinned = function (event) {
            var dtl = event.detail;
            if (dtl.column.field === 'LastName') {
                dtl.insertAtIndex = 0;
            }
        }
        igRegisterScript("onColumnPinned", onColumnPinned, false);

**Comment by agoldenbaum** [comment]
I added the JS handler and mentioned "ColumnPinnedScript" in a recent PR. Will close this once I can verify it on staging

**Comment by agoldenbaum** [comment]
Verified on staging
