### ISSUE TITLE
IgbGrid Cell Validation on Edit Topic has conflicting column names in text and sample

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-docs#597]
goto: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/cell-editing#cell-validation-on-edit-event

"The CellEdit emits whenever any cell's value is about to be committed. In our _HandleCellEdit_ definition, we need to make sure that we check for our specific column before taking any action:

If the value entered in a cell under the _Ordered column_ is larger than the available amount (the value under Units in Stock), the editing will be cancelled and a toast with an error message will be displayed."

==> _HandleCellEdit_ is called WebGridEditingEventsCellEdit in actual sample
==> _OrderedColumn_ is units on Order in actual sample

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-docs/pull/772
