### ISSUE TITLE
IgbGrid CellEditing link to "Build CRUD operations with the Grid" throws 404

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-docs#598]
goto https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/cell-editing#additional-resources

click on link to "Build CRUD operations with the Grid"

page is not found

**Comment by agoldenbaum** [comment]
@IGvaleries  - This is fixed on staging. Marking the issue closed
