### ISSUE TITLE
Perform the following changes

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-xplat-docs#6]
Xplat docfx changes

- [x] Change demo headers to Platform X Example
- [x] Add alt attribute to all iframes based on the demo header
- [x] Update web.config with redirect rules and .html rewerite
- [x] (docfx-template) Add call to action description for all topics
- [x] (docfx-template) Remove .html from internal links part of all topics
- [x] (docfx-template) Remove all .html from TOC
- [x] Generate sitemap.xml
- [x] Remove all .html from sitemap - use the post process created by Dobri
- [x] Remove .html from URL - check all rewrite rules
- [x] Structure review of all topics

**Comment by zdrawku** [comment]
@HUSSAR-mtrela will handle this point -

>  Update web.config with redirect rules and .html rewerite

**Comment by HUSSAR-mtrela** [comment]
@zdrawku all these items should be completed now in xplat repo and angular repo
