### ISSUE TITLE
IgbGrid Editing topic mentions Batch Editing and Build Crud operations

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-docs#600]
goto : https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/editing

as batch editing is not yet available the docs should not mention this feature

also at the end og the topic (in Additional Resources) there is a link to Build CRUD operations which should be removed as this is not yet available

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-docs/pull/645
