### ISSUE TITLE
Blazor Grid Group By topic says IgbDataGrid instead of IgbGrid

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-docs#601]
goto: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/groupby

there are several refernces  /links to IgbDataGrid

**Comment by HUSSAR-mtrela** [comment]
fixed on staging
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/groupby
