### ISSUE TITLE
Web Components help page: links to community pages are not working

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-xplat-docs#607]
When I try to jump to two links under "Additional Resources" section, neither works. Can you fix these please?
https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/overview#additional-resources

![image](https://user-images.githubusercontent.com/14340675/204177609-ef65671b-7761-4109-915d-7a09488b84f5.png)

**Comment by HUSSAR-mtrela** [comment]
already fixed
