### ISSUE TITLE
API - Missing links for IgcAccordionComponent

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-xplat-docs#620]
## Description  
All Accordion related links lead to non-existing pages.

## Steps to reproduce  
1. Go to https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/accordion
2. Click some API link

##Result
"404 File or directory not found"

Example: https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcaccordioncomponent.html

**Comment by damyanpetev** [comment]
It seems this is true for all links for components from `igniteui-webcomponents` package. For example, in https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/rating:
- links to https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcratingcomponent.html (404)
- but it should be https://www.infragistics.com/products/ignite-ui-web-components/docs/typescript/latest/classes/igcratingcomponent.html

Same for Select and so on. Guessing @HUSSAR-mtrela is already aware of this, just adding more info to the issue.
