### ISSUE TITLE
Blazor row actions sample should only have row editing turned on since there is no commit button

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-docs#624]
goto  (https://staging.infragistics.com/blazorsite/components/grids/grid/row-actions#custom-implementation)

sample enables row and batch editing but there is no way to commit an edit. Instead the sample should just enable row editing so the edits can be committed thru the interface

**Comment by mddifilippo89** [comment]
There is a "Done" and "Cancel" button like Angular. 
eg.
https://www.infragistics.com/angularsite/components/grid/batch-editing

I don't see a difference between the two samples.

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-blazor-examples/pull/298

&

https://github.com/IgniteUI/igniteui-xplat-examples/pull/155
