### ISSUE TITLE
API - Broken links in WC documentation

### ISSUE THREAD

**Issue by nikolam001** [IgniteUI/igniteui-xplat-docs#692]
Large amounts of links currently point to non-existent pages ( error 404 ). Either paths are wrong or these pages do not exist.

All links mentioned below are mentioned in various docs in `grid` section ( pretty much all files have some of the missing links mentioned ).

**NOTE:** There might be even more broken links.

Missing topic links:

- https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/pivot-grid/pivot-grid.md

Missing API links:

- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igctreeitemcomponent.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccombocomponent.html#disablefiltering
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccombocomponent.html#casesensitiveicon
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccombocomponent.html#groupkey
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccombocomponent.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccombocomponent.html#valuekey
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcpivotgridcomponent.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcpivotdataselectorcomponent.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcpivotdimension.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcpivotvalue.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#locale
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccolumn.html#datatype
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccolumn.html#pipeargs
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#enablesummaries
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#disablesummaries
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccolumn.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccolumn.html#sortstrategy
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#sortingexpressions
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccolumn.html#datatype
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#sortheadericontemplate
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#sortascendingheadericontemplate
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#sortdescendingheadericontemplate
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcsortingexpression.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridrow.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#cellselection
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccolumn.html#width
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igccolumn.html#searchable
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridcomponent.html
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#findprev
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#findnext
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#perpage
- https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcgridbasedirectivecomponent.html#clearsearch

**Comment by nikolam001** [comment]
FYI @dkamburov

**Comment by HUSSAR-mtrela** [comment]
All API links to pivot grid are broken because we need a new build of API docs.

**Comment by HUSSAR-mtrela** [comment]
this should be fixed by this PR https://github.com/IgniteUI/igniteui-xplat-docs/pull/905

**Comment by HUSSAR-mtrela** [comment]
fixed on production
