### ISSUE TITLE
Broken Grid link in the marketing WC page

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-xplat-docs#694]
Go to the main [WC page](https://www.infragistics.com/products/ignite-ui-web-components) and search for the Data Grid under the Web Components Grids and Lists. The link is broken.

![image](https://user-images.githubusercontent.com/2621802/220858189-3a689ae7-a40b-4555-b295-3215eccdc222.png)

**Comment by pamelabrasil** [comment]
Marketing pages are now correct and do not have a broken link
