### ISSUE TITLE
Grid editing topic exposes "test" strings

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-xplat-docs#696]
Open the [topic](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/editing#editing-templates)
![image](https://user-images.githubusercontent.com/11193764/221897513-9cf3cf17-b780-4794-87cc-d09f26272ee8.png)

**Comment by HUSSAR-mtrela** [comment]
fixed on staging
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/editing
