### ISSUE TITLE
Add sample for IgbGrid showing cascading behavior with multi-column-combobox components

### ISSUE THREAD

**Issue by Svetloslav15** [IgniteUI/igniteui-xplat-docs#699]
Create a grid sample showcasing cascading behavior. Add 2 columns with multi-column-combobox components, and second one should be populated based on the value of the first. 
For example select "Country" from the first combo and upon the selection, the second one should prefill States based on that country.

**Comment by mddifilippo89** [comment]
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/cascading-combos
