### ISSUE TITLE
Changing-Docs section in the README is missing

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-docs#728]
Please add [Changing-Docs](https://github.com/IgniteUI/igniteui-xplat-docs#Changing-Docs) in the README.md file.

`Changing Docs` is present in the TOC but the topic is missing

![image](https://user-images.githubusercontent.com/52001020/227507130-f5096f41-66d0-4d47-a3eb-02f5eec78568.png)

**Comment by mddragnev** [comment]
@radomirchev I think that there is no use of that TOC section. All the information exists somewhere inside the other section within the README. Thus, I`m removing it.
