### ISSUE TITLE
Blazor Dockmanager customization topic is missing sample

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-docs#731]
goto: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/dock-manager#customization

scroll to after code snippet

Topic says "If everything went well, we should now have a DockManager with customized icons and tab area. Let's have a look at it:" but is not followed by the example

**Comment by agoldenbaum** [comment]
Fixed on staging
