### ISSUE TITLE
Chart samples and documentation not up to date

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-xplat-docs#74]
1) Open the following bar chart [topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-type-category-bar-series#required-axes) and [sample ](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos-dv/charts/data-chart-type-category-bar-series)
2) Observe the errors in the browser console related to: 

Template parse errors:
.....
'**igx-numeric-x-axis**' is not a known element:
'**igx-category-y-axis**' is not a known element:
**'igx-bar-series'** is not a known element:
....

The stakblitz sample requires the corresponding modules to run:
Add the following:
```
  import { 
     IgxNumericXAxisModule,
     IgxCategoryYAxisModule,
     IgxBarSeriesModule,
.... .....
 } from "igniteui-angular-charts";

...
  imports: [
 ...
    IgxNumericXAxisModule,
    IgxCategoryYAxisModule,
    IgxBarSeriesModule
  ],
```

3) The topic does not reflect the need for these modules.

4) When applying the following topic [section ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-type-category-bar-series#required-modules) and importing these

`import { **IgxNumericXAxis**, **IgxCategoryYAxis**, **IgxBarSeries** } from "igniteui-angular-charts";`

Throws the following error:
Module '"../../node_modules/igniteui-angular-charts/igniteui-angular-charts"' has no exported member 'IgxNumericXAxis'.ts(2305)

5) This is not an isolated case of not working samples and wrong/not updated/misleading documentation. 
- I suggest checking all samples to see if the samples are running at all and fix the errors if such.
- Go trough the documentation topics and test the code snippets so these are updated as well.

**Comment by HUSSAR-mtrela** [comment]
@IvayloG this topic and sample was replaced by
infragistics.com/products/ignite-ui-angular/angular/components/charts/types/bar-chart
