### ISSUE TITLE
Update/Remove - Custom Implementation Doesnt' Work in Blazor/WC

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-xplat-docs#746]
https://github.com/IgniteUI/igniteui-xplat-docs/blob/29552a75ed061b0825cbd23f22e6210777f517f4/doc/en/components/grids/_shared/row-actions.md#custom-implementation

**Comment by mddifilippo89** [comment]
@dkamburov Is this completed?

**Comment by dkamburov** [comment]
I think so

**Comment by mddifilippo89** [comment]
@gmurray81 @ig-robstoffers 
Is this merged into the product yet?
