### ISSUE TITLE
Altering the API doc paths to deal with new uri paths in new versions of TypeDoc

### ISSUE THREAD

**Issue by gmurray81** [IgniteUI/igniteui-xplat-docs#825]
We are updating typedoc to a newer version in our builds necessitated by the changes to the ig typedoc theme. This is making it more difficult to keep the doc as one root with all the types at the root, so newer versions will have the package names as part of the uri.

To accommodate for this I'm amending the API maps emitted by the product to contain information about the package name so that we can use that appropriately in the API doc links. This issue is for tracking the work of updating the generation of the output doc with the new API map information.

**Comment by HUSSAR-mtrela** [comment]
closing this issue since api mappings have been updated
