### ISSUE TITLE
Blazor - The step "Add Script Reference" lacks in .NET 6 application, although it is necessary.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-xplat-docs#940]
Open the following pages:
- https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/general-getting-started#net-6-applications
- https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/general-getting-started-blazor-client#net-6-applications

-> There is no step to add script reference in the .NET 6 application.
<script src="_content/IgniteUI.Blazor/app.bundle.js"></script>

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-docs/pull/1088
